name: build-and-test-backend

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: Restore tool dependencies
        run: dotnet tool restore
      - name: Build
        run: dotnet build
      - name: Check formatting
        run: dotnet format --verify-no-changes
      - name: Run tests
        run: dotnet test --verbosity normal